<a href="https://colab.research.google.com/github/ahnafia/Learning_Pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors are just numpy arrays but optomized for GPUs

In [1]:
import torch
import numpy as np

In [2]:
#Normal array
arr = np.array([i for i in range(10)])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Tensors!!
tensor_example = torch.tensor([i for i in range(10)])
tensor_example

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Couple of Tensor operations

In [7]:
my_tensor = tensor_example.reshape(2,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
my_tensor2 = tensor_example.view(2,5)
my_tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
tensor_example[1] = 40
tensor_example

tensor([ 0, 40,  2,  3,  4,  5,  6,  7,  8,  9])

In [10]:
my_tensor2
#Tensors update, they dont make copies

tensor([[ 0, 40,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [12]:
#Math Operations
print(my_tensor2 + my_tensor) #Tensor.add does the same thing
print(my_tensor2 * my_tensor)
print(my_tensor2 - my_tensor)
print(my_tensor2 / my_tensor)
#FOr modulus I can use torch.remainder()

tensor([[ 0, 80,  4,  6,  8],
        [10, 12, 14, 16, 18]])
tensor([[   0, 1600,    4,    9,   16],
        [  25,   36,   49,   64,   81]])
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])
tensor([[nan, 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [15]:
#Reassignment with an underscore
tensor_2 = torch.tensor([i for i in range(10)])
tensor_example.add_(tensor_2)
tensor_example

tensor([ 0, 41,  4,  6,  8, 10, 12, 14, 16, 18])